version: "3.8"
services:
  validator:
    image: solanalabs/solana:v1.17.0
    command: solana-test-validator --reset --rpc-port 8899 --faucet-port 9900
    ports:
      - "8899:8899"
      - "9900:9900"
    volumes:
      - validator-ledger:/ledger
volumes:
  validator-ledger:
